# Generated by Django 3.2.13 on 2022-06-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peingapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='quesiton',
            new_name='question',
        ),
        migrations.AddField(
            model_name='answer',
            name='author',
            field=models.CharField(default='admin', max_length=200),
        ),
    ]
